language: ruby
rvm:
- 2.5
env:
  global:
  - CC_TEST_REPORTER_ID=6814cdac7ff409c251af3cc20c537c54f45c3837928bb60859b48ecce17e269c
  matrix:
  - COVERAGE=true
services:
- postgresql
before_script:
- bin/yarn
- bin/rails db:migrate RAILS_ENV=test
- bundle exec rails db:create
- bundle exec rails db:migrate
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bin/rails test
- bin/yarn test
- bin/webpack-dev-server --host 127.0.0.1
- bundle
- bundle exec rspec
- bundle exec rubocop
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"